name: Build DLL

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Visual C++ environment
      uses: ilammy/msvc-dev-cmd@v1
      
      - name: Set up Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"

    - name: Build DLL
      run: |
        cl /LD /I.lua/include mylib.cpp /Femylib.dll
        dir

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mylib.dll
        path: mylib.dll
