name: Build add_DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y g++ lua5.1 liblua5.1-dev
    - name: Build DLL
      run: g++ -shared -fPIC -o add.dll add.cpp -I/usr/include/lua5.1 -llua5.1
    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: add.dll
        path: add.dll
