name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64" >> $GITHUB_PATH
        echo "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64" >> $GITHUB_PATH
    - name: Build EXE
      run: |
        cl /EHsc /Feadd.exe add.cpp
    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: addc.exe
        path: addc.exe
