name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        git clone https://github.com/facebookarchive/luaffifb.git
        cd luaffifb
        msbuild luaffifb.sln /p:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ffi.dll
        path: luaffifb/Release/ffi.dll
