name: Build and upload C++ code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Compile the code
      run: |
        cd ${{ github.workspace }}
        g++ addc.cpp -o addc.exe

    - name: Upload the binary
      uses: actions/upload-artifact@v2
      with:
        name: addc-binary
        path: ${{ github.workspace }}/addc.exe
