name: Build FFI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    - name: Install dependencies
      run: |
        choco install mingw
        choco install make
        choco install luarocks
        choco install windows-sdk-10-version-2004-all

    - name: Add cl to PATH
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Find stdint.h
      run: |
        $location = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10" -Filter stdint.h -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($location) {
          echo "Found stdint.h at $($location.FullName)"
          echo "CFLAGS=-I$($location.Directory)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        } else {
          echo "Could not find stdint.h"
        }

    - name: Build FFI
      run: |
        git clone https://github.com/facebookarchive/luaffifb.git
        cd luaffifb
        make CFLAGS="${{ env.CFLAGS }}"

    - name: Copy FFI to project
      run: |
        New-Item -ItemType Directory -Force -Path .\ffi\
        Copy-Item .\luaffifb\ffi.dll .\ffi\
