name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Install LuaRocks
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks

    - name: Cross-compile FFI
      run: |
        git clone https://github.com/facebookarchive/luaffifb.git
        cd luaffifb
        make CC=x86_64-w64-mingw32-gcc

    - name: Copy FFI to project
      run: |
        mkdir -p ffi
        cp luaffifb/ffi.dll ffi/
