name: Build DLL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MSVC
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build DLL
      run: |
        cd mydll
        msbuild mydll.vcxproj /p:Configuration=Release

