name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build solution
      run: msbuild mydll.sln /p:Configuration=$env:BUILD_CONFIGURATION

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mylib.dll
        path: path/to/mylib.dll
